# Site settings
title: Sunbird Docs
name: Sunbird Docs
email: info@sunbird.org
description: "Sunbird Site"
environment: production
permalink: pretty
markdown: kramdown
highlighter: pygments
safe: false
ga: UA-106552125-1
anchorPrefix: link
tocTopTag: h2
showToggleButton: true
showSearch: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "apis"
    values:
      layout: "default"
exclude:
- .gitignore
- README.md
- ingredients
- Gemfile
- Gemfile.lock
- .sh

sass:
  sass_dir: css
 
